name: Deploy PredyxLab UI

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/azure-static-web-apps-agreeable-hill-0d5faf500.yml"
                          

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN}}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "frontend/predyxlab-ui"
          output_location: "build"
          app_build_command: "npm install && npm run build"
